name: Version

on:
  workflow_dispatch:
    inputs:
      tag:
        type: choice
        description: 'Tag to release'
        options:
          - latest
          - next
        required: true
        default: "latest"

jobs:
  release:
    name: Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: yarn

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          version: yarn version:${{github.event.inputs.tag}}
          createGithubReleases: false
          commit: "chore(release): bump version"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
